### ISSUE TITLE
Add a PluginCallbackTask - an extended PluginTask that allows Closures to be used for tasks instead

### ISSUE THREAD

**Issue by msjyoo** [PEMapModder/StdPocketLib#1]

**Comment by PEMapModder** [comment]
It's named `CallbackPluginTask`, completed on my local branch.

Do you have any suggestions on its structure? Like the onCompletion callback? Or args?

**Comment by PEMapModder** [comment]
I'm thinking if I should let this plugin handle cooperative things too, like those click-to-act callbacks, etc.
